name: Kactl CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
    - name: Build pdf
      run: make kactl

    - name: Generate unique release tag
      id: tag
      run: |
        TAG="release-$(date +'%Y%m%d-%H%M%S')"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: kactl-pdf
        path: kactl.pdf

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.tag.outputs.tag }}
        tag_name: ${{ steps.tag.outputs.tag }}
        files: kactl.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Run compiles
      run: make test-compiles
    - name: Run stress tests
      run: make test
